user: ec2-user
group: ec2-user
remote_home_dir: /home/ec2-user
remote_nodejs_dest_dir: "{{ remote_home_dir }}/windfire-restaurants-node"
remote_nodejs_app_dir: "{{ remote_home_dir }}/windfire-restaurants-node/app"